# Generated by Django 5.1.12 on 2025-09-16 23:12

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="studentprofile",
            name="student_profile_balance_gte_0",
        ),
        migrations.RenameIndex(
            model_name="studentprofile",
            new_name="studprof_approved_idx",
            old_name="student_pro_is_appr_cc3155_idx",
        ),
        migrations.RenameIndex(
            model_name="studentprofile",
            new_name="studprof_type_idx",
            old_name="student_pro_type_bbdf86_idx",
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="UZS-like fixed precision; non-negative.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="is_approved",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="type",
            field=models.CharField(
                choices=[("online", "Online"), ("offline", "Offline")],
                db_index=True,
                default="online",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(fields=["created_at"], name="teachprof_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)), name="studprof_balance_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_approved", True), ("type", "offline")),
                    models.Q(("is_approved", False), ("type", "online")),
                    _connector="OR",
                ),
                name="studprof_type_matches_approval",
            ),
        ),
    ]
