# Generated by Django 5.1.12 on 2025-09-12 15:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("telegram_id", models.BigIntegerField(db_index=True, null=True)),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("register", "Register"), ("login", "Login")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("consumed", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "db_table": "verification_codes",
                "indexes": [
                    models.Index(
                        fields=["telegram_id", "created_at"],
                        name="verificatio_telegra_9f313f_idx",
                    ),
                    models.Index(
                        fields=["purpose", "created_at"],
                        name="verificatio_purpose_d6b66b_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="verificatio_expires_bef114_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("code__regex", "^\\d{6}$")),
                        name="verification_code_six_digits",
                    )
                ],
            },
        ),
    ]
