# Generated by Django 5.1.12 on 2025-09-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="verificationcode",
            name="verificatio_telegra_9f313f_idx",
        ),
        migrations.RemoveIndex(
            model_name="verificationcode",
            name="verificatio_purpose_d6b66b_idx",
        ),
        migrations.RemoveIndex(
            model_name="verificationcode",
            name="verificatio_expires_bef114_idx",
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="expires_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(
                fields=[
                    "telegram_id",
                    "purpose",
                    "consumed",
                    "expires_at",
                    "created_at",
                ],
                name="vc_tid_purp_cons_exp_cre_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationcode",
            index=models.Index(
                fields=[
                    "telegram_username",
                    "purpose",
                    "consumed",
                    "expires_at",
                    "created_at",
                ],
                name="vc_tuser_purp_cons_exp_cre_idx",
            ),
        ),
    ]
