# Generated by Django 5.1.12 on 2025-09-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_remove_verificationcode_verificatio_telegra_9f313f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="purpose",
            field=models.CharField(
                choices=[("register", "Register"), ("login", "Login")], max_length=10
            ),
        ),
    ]
