# Generated by Django 5.1.12 on 2025-09-16 23:12

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="users_phone_idx",
            old_name="users_phone_n_a3b1c5_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_role_idx",
            old_name="users_role_0ace22_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="users_tgid_idx",
            old_name="users_telegra_d76140_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                help_text="Stored lowercased; unique (case-insensitive) when not null.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("phone_number__regex", "^\\+?[1-9]\\d{7,14}$")),
                name="users_phone_e164_like",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("telegram_username"),
                condition=models.Q(("telegram_username__isnull", False)),
                name="users_tg_username_ci_uniq",
            ),
        ),
    ]
